### ISSUE TITLE
Hw4

### ISSUE THREAD

**Issue by rahlk** [maverickmishra/x9115NVN#5]
##### Remarks:

I am surprised you are getting x=0.9999 within 1000 iterations! 
- [ ] In [Line 40 of schaffer_random.py](https://github.com/maverickmishra/x9115NVN/blob/master/hw/code/4/schaffer_random.py#L40) you use `random.random()` to find neighbours, this function has a range of 0 - 1, but x must lie between 1e-5 to 1e5.
- [ ] Try the following neighbor functions:
  - `random.uniform(-10e5,10e5)`: Random number in the entire range. Or, better yet,
  - Search for neighbor using the current s value. I recommend this: 

``` python
           def neigh(x,xmax=1e-5,xmin=1e+5):
             rad = min(x-xmin, xmax-x)
             return random.uniform(x-rad,x+rad)
```

**Comment by aNa-k1n** [comment]
With x in Range {-100000,100000}
i.e 
DOMAIN_MIN = -100000
DOMAIN_MAX = 100000
x = random.uniform(DOMAIN_MIN,DOMAIN_MAX)

we are getting very inconsistent best solutions and that too it not near to 1

by increasing the value of kmax (tried with kMax = 1000000)...i am getting x near to 1.

are these observation correct and acceptable. ?
